### ISSUE TITLE
Submit to FreeCAD-macros

### ISSUE THREAD

**Issue by luzpaz** [dprojects/getDimensions#1]
Please add https://github.com/dprojects/getDimensions to https://github.com/FreeCAD/FreeCAD-macros/ by forking and submitting a PR. Also can you create an animated gif of the macro in action ?

**Comment by dprojects** [comment]
I don't know how they keep track on changes if they require here https://www.freecadweb.org/wiki/index.php?title=Macros_recipes submitting the macro code instead of link to the always actual macro code (also with other language versions). Doesn't make sens to me :-(
