### ISSUE TITLE
pdf export of toPrint cropped?

### ISSUE THREAD

**Issue by ergodicbreak** [dprojects/getDimensions#13]
Hello, I'm tracking down whether this is an issue with getDimensions macro or FreeCAD. When I create the cutlist, and export toPrint, the top few lines of text are cut off in the exported PDF. I can see them in FC, but not in my PDF viewers (Firefox and Okular). 

Is this an issue for anyone else?

**Comment by dprojects** [comment]
Yes, if the report is bigger than the pdf page you should rather use [sheet2export](https://github.com/dprojects/sheet2export) tool and export spreadsheet to HTML. Currently FreeCAD not support automatic multi-page TechDraw constructor.
