### ISSUE TITLE
cutlist object list not ordered the same as in Tree window

### ISSUE THREAD

**Issue by ergodicbreak** [dprojects/getDimensions#14]
Maybe I'm not choosing the right options, but when I create the cutlist the ordering of objects is not the same as the tree window, so parts that should be grouped together are not. 

How does getDimensions determine the order of the object list?

**Comment by dprojects** [comment]
To create report with groups you should rather use [g - report type](https://github.com/dprojects/getDimensions/tree/master/Docs#g---report-type)
