### ISSUE TITLE
Remove hidden parts from BOM

### ISSUE THREAD

**Issue by gianarb** [dprojects/getDimensions#16]
Hello

Thank you for the hard work, I am wondering what I am doing wrong but I am trying to use this macro with Assembly 4 and I know this is designed to work with Woodworking Workbench but I am wondering if I can make this to work enough for my use case.

The FreeCAD project contains the parts AND the assembly all together and when I generate the BOM I get both parts and the part of the assembly into it.

My desire is to get only the parts from the Assembly 4 workbench. I tried to play with the visibility, I have hidden all the single parts leaving only the one in the Assembly 4 and I set Visibility to `on` but I don't get what I expect (I get only two parts, not sure why)

I think I can share my project here if it helps

[assembly-v2.zip](https://github.com/dprojects/getDimensions/files/14670214/assembly-v2.zip)

**Comment by dprojects** [comment]
The base002 object is PartDesign::Pocket type, if you play with visibility the hidden base will not be calculated.
The base003 object is the object that should be calculated, I mean should be visible if you play with visibility.

So... you have to make visible Pads no its decorations if you play with visibility and you want to turn off some parts. Maybe there is other solution but I am not familiar with Assembly 4 so much.

and the file sample with visible Pads, calculated 3 as it is at 3D view: [assembly-v2.FCStd.zip](https://github.com/dprojects/getDimensions/files/14671393/assembly-v2.FCStd.zip)

Let me know if this should be improved somehow...
