### ISSUE TITLE
FreeCAD issue #2957: Support for direct printing

### ISSUE THREAD

**Issue by luzpaz** [dprojects/getDimensions#2]
https://freecadweb.org/tracker/view.php?id=2957
Can you further elaborate on what you want the final product to look like?

**Comment by dprojects** [comment]
For example: on "Spreadsheet" tab I would like to have button with print option. The print button could transform current spreadsheet table into pdf document and open box for print it. This should preserve text color and other formating.

**Comment by luzpaz** [comment]
Check out https://forum.freecadweb.org/viewtopic.php?f=4&t=25691&p=203175#p203175
