### ISSUE TITLE
Quantity of array of array objects

### ISSUE THREAD

**Issue by LeonB** [dprojects/getDimensions#9]
I have a divider I array'ed into 11 separate pieces. Then that array is array'ed for a second row:

<img width="603" alt="Screenshot 2022-07-13 at 22 32 51" src="https://user-images.githubusercontent.com/3979/178830175-724c052c-676c-4cda-b7fc-2fde7b7884c1.png">

getDimensions reports 11 pieces:

<img width="821" alt="Screenshot 2022-07-13 at 22 32 27" src="https://user-images.githubusercontent.com/3979/178830342-0a1fc55e-8dfc-4968-bcef-a7528b7b37f9.png">

I would expect 22. I've attached my test file:

[test-arrays.FCStd.zip](https://github.com/dprojects/getDimensions/files/9105882/test-arrays.FCStd.zip)

Not a very big issue! Just something I noticed.

**Comment by dprojects** [comment]
Yes, this is because the array on array is not supported, only the array on "furniture part" - at base element. The array wasn't made to call it at any object. Probably it can be fixed by call recursively scanObjects instead of furniture part. I will look into that someday if this can be improved.

**Comment by dprojects** [comment]
Support for array on array has been added. I use caller feature instead of scanObjects because it was little tricky with the base hidden object.
